[Feature] First draft of populated sets
Big-Life-Lab/PHES-ODM-Doc pull request #22
Opened 2023-01-17 15:30 UTC by rvyuha

The changed file contains the first draft of sets

2023-01-18 19:05 UTC, yulric requested changes
1. Can we create a function that wraps li and ul tags within a string. It looks like we'll be using it in multiple reference list items.

2023-02-03 16:34 UTC, yulric requested changes

2023-02-03 16:34 UTC, yulric commented on qmd/sets.qmd
> +list_creation <- function(string_to_append, list_values){
Rename to `create_html_list`. Functions should start with verbs.

2023-02-03 16:34 UTC, yulric commented on qmd/sets.qmd
> +list_creation <- function(string_to_append, list_values){
I don't think the appending needs to be done in this function i.e. we don't need the `string_to_append` parameter,

A function should try to have only one responsibility and there's no need for this function to have the responsibility of the appending.

2023-02-03 16:34 UTC, yulric commented on qmd/sets.qmd
> +list_creation <- function(string_to_append, list_values){
Add Roxygen comment.

2023-02-03 16:34 UTC, yulric commented on qmd/sets.qmd
> +  string_to_append <- glue::glue('{string_to_append}
We can insert both ul tags at the end just like the li tags in line 21-22

2023-02-03 16:34 UTC, yulric commented on qmd/sets.qmd
> +handle_empty_character_vector <-
Rename to `replace_if_empty_character_vector`

2023-02-03 16:34 UTC, yulric commented on qmd/sets.qmd
> +  function(check_vector, replace_string) {
Rename to `vector_to_check`. Variable names should not start with verbs.

2023-02-03 16:34 UTC, yulric commented on qmd/sets.qmd
> +  function(check_vector, replace_string) {
Rename to `str_replace`. Variable names should not start with verbs.

2023-02-03 16:34 UTC, yulric commented on qmd/sets.qmd
> +    unique_part_IDs <- unique(current_set_ID_rows$partID)
Rename to `unique_set_ID_rows`

2023-02-03 16:34 UTC, yulric commented on qmd/sets.qmd
>        part_info <- parts_table[parts_table$partID == part_ID,]
Rename to `set_info`

2023-02-03 16:34 UTC, yulric commented on qmd/sets.qmd
> +      part_label <- handle_empty_character_vector(part_label, "Part Label is missing at the moment")
Rename to `set_label`

2023-02-03 16:34 UTC, yulric commented on qmd/sets.qmd
> +    list_values <- list()
Rename to `curent_set_type_content`

2023-02-14 21:46 UTC, DougManuel commented
`setType` — see example below.

- Change to Header #2. 
- partLabel only for the header.
- Add anchor (the anchor should be added automatically).
- partID in the same format as for Tables; on a separate line.

![Screenshot 2023-02-14 at 4 42 18 PM](https://user-images.githubusercontent.com/13246138/218869835-1723d957-3b75-45d4-a0b7-605576e922f2.png)

2023-02-14 22:06 UTC, DougManuel commented
For `setID`. See example below.

- header 3.
- with anchor.
- setID label only. for `booleanAggrSet` the label is `Boolean aggregation set`.
- remove `set members:`
- Format similar to headers in tables.
     - bullets.
     - setLabel (partLabel) in bold. 
     - followed by part ID in parenthesis `()` and a period `.`
     - followed by the setID partDesc
     - followed by: 'Status:' (followed by the status 'active' or 'depreciated'. 'First released:' (followed by release version). 'Last updated:' followed by last updated.

Put together the example below would be:

--------


## Aggregation set
partID: [aggSet](https://docs.phes-odm.org/parts.html#aggset). Sets of aggregations that can be used for measures. Examples of aggregation sets include logarithm, linear and boolean.

### Boolean aggregation set
- **Single** (sin). This value is not an aggregate measurement in any way (ie. not a mean, median, max or any other) and can be a replicate value. Status: active. First released: 2.0.0. Last updated: 2.0.0.


--------







![Screenshot 2023-02-14 at 4 47 38 PM](https://user-images.githubusercontent.com/13246138/218870668-a707393e-2958-417b-b79d-f382339f0a05.png)

2023-02-14 22:08 UTC, DougManuel requested changes
@rvyuha I made changes to the formatting in the comments section. 

Could you modify with those changes and then I'll review further?

2023-02-21 18:25 UTC, rvyuha commented
@yulric and @DougManuel ready for further review

2023-02-21 19:25 UTC, rvyuha commented
@yulric Ready for review

2023-02-21 21:06 UTC, DougManuel commented
1. The organization with the listSet is good. But please put in alphabetical order within the listSet header. 

1. However, you are missing those lists within the listSet. For example, you are missing the first 'dataType' list. We want lists for everything in the sets tab (setTypes except dictSet) AND all lists for list generated when you select for partType for the partIDs in listSet.

1. In the example below. Could you:
      - Put a space between ​compartment​ and ​(air)​ 
      - Make a link for ​air​ to its partID in the parts.html page. 
      - Put `Status: active. First released....`on a new line.
  
<img width="773" alt="Screenshot 2023-02-21 at 3 48 37 PM" src="https://user-images.githubusercontent.com/13246138/220458120-76542480-8162-4c92-9546-1098e7910e8c.png">

2023-02-26 12:29 UTC, merged