Sets lists implementation
Big-Life-Lab/PHES-ODM-Doc pull request #27
Opened 2023-02-28 15:32 UTC by rvyuha

Creating temporary PR to get feedback on display format for lists.

2023-02-28 17:56 UTC, rvyuha commented
Something of note:
Identical sets and lists do not have identical displays.
Using the side bar navigation takes you to the first instance of the anchor.

2023-02-28 20:26 UTC, DougManuel requested changes
1) There is an error in the output for the first set, 

```
## Aggregations { #aggregation } [(aggregation)](file:///Users/dmanuel/github/PHES-ODM-Doc/docs/parts.html#aggregation). Statistical measures used to report a measure. Each measure reported as a number should be reported with an aggregation.
```

1) For all heading # 3: (i.e. `Boolean aggregation set`), add the following.
- On the next line, print the (partID). label. description. instruction.
- Then: status, first released, last updated.
The partID should have the link to the partID.

1) For `Category Sets`. 
- Change all the Heading # 3 to heading #2. (meaning move heading three out of the nest within `Category Sets`. 
- Remove heading #3 (category sets).

We can merge to main after that update.

2023-02-28 20:32 UTC, DougManuel commented
One additional feature that is highish priority is to update all links **to** the sets page. 
- Any reference to a partID attribute that doesn't begin with 'na' and ends in 'catSet' or 'Set' should link to set.html. The link is currently parts.html.
- This applies to the following attributes:
     - Compartment Set
     - Unit Set ID
     - Aggregation Scale ID
     - Quality Set ID
     - Category Set ID
     - Unit Set ID

2023-03-01 19:08 UTC, DougManuel commented
The PR looks good. The first part is rendering without a problem.

The version yesterday had a collapsable navigation bar on the right side, but it doesn't today. I like the collapsable nav. 

I pushed version rc.3.10. Why don't you update with that version and we'll see if the duplicates get removed. Then we should be GTG.

2023-03-02 20:19 UTC, yulric requested changes

2023-03-02 20:19 UTC, yulric commented on qmd/sets.qmd
>      list_values <- list()
Should be named more specific, right now I don't know what list values its supposed to hold. For example, `set_cat_list_values`.

2023-03-02 20:19 UTC, yulric commented on qmd/sets.qmd
> +        '**{sub_category_label}** <a href=\"/parts.html#{sub_category_ID}\">({sub_category_ID})</a>. {sub_category_description} </br>Status: {sub_category_status}. First released: {sub_category_first
This is the same template string as on lines https://github.com/Big-Life-Lab/PHES-ODM-Doc/blob/sets-lists-implementation/qmd/sets.qmd#L195 and https://github.com/Big-Life-Lab/PHES-ODM-Doc/blob/sets-lists-implementation/qmd/sets.qmd#L280. Probably should be moved into a function.

2023-03-02 20:19 UTC, yulric commented on qmd/sets.qmd
> +    '## {category_label} {{ #{category_set_ID} }}
This template string is the same as on lines https://github.com/Big-Life-Lab/PHES-ODM-Doc/blob/sets-lists-implementation/qmd/sets.qmd#L233-L236 and https://github.com/Big-Life-Lab/PHES-ODM-Doc/blob/sets-lists-implementation/qmd/sets.qmd#L89-L91 and should be moved into a function.

2023-03-03 12:58 UTC, yulric commented
I also noticed that the content structure for the different set types (list, catSet, setType) are the same. The main difference is what the grouping is (list, catSet, setID) and what the categories are in that grouping. I believe the code can be significantly reduced and made less confusing if we make one function to render each grouping and use it everywhere. Let me know if this does not make sense and we can discuss it.

2023-03-03 13:16 UTC, DougManuel commented
Yes, those lists are the same, essentially. I am talking this morning to @mathew-thomson about a modest clean-up renaming of these parts (spurred by this work). It shouldn't change the structure and location of the parts -- at least for version 2. I'll put a Discourse post in this discussion.

2023-03-03 14:43 UTC, merged