Refactor constants into modules
Big-Life-Lab/PHES-ODM-Doc pull request #37
Opened 2023-04-11 13:32 UTC by rvyuha

Refactored contants.R into 3 new module files.
- dictionary-module.R Stores strings for dictionary sheets access as well as different dictionary-specific qmds.
- parts-module.R Stores strings related to the dictionary parts sheet.
- sets-module.R Stores string related to the dictionary sets sheet.
- Removed references to constants.R with new module files
- Removed constants.R

2023-04-12 15:53 UTC, yulric requested changes
* Can we standardize how we represent the information for the columns in a sheet? This can be done in another PR
	* I propose the following schema:
		* ```
		  list(
			  <column_list_name> = list(
                    // Contains the name of the column in the sheet
                    name = <column_name>,
				  // This is added only if the column is categorical
				  categories = list(
					  <category_list_name> = <category_identifier>
				  )
			  )
		  )
		* For the parts sheet the `list` would be (this list is abbreviated),
			* ```
			  list(
				  part_id = list(
					  name = "partID",
				  ),
				  part_type = list(
					  name = "partType",
					  categories = list(
						  tables = "tables"
					  )
				  )
			  )
		* Dynamic columns, columns whose names we don't know beforehand, like the table columns in the parts sheet are problematic.
			* We can store the information for those columns in a variable and then dynamically add to the schema in the code
			* For example, 
			```
			 table_columns_metadata <- list(
			     categories = list(
				primary_key = "pK",
				foreign_key = "fK",
				header = "header",
				not_applicable = "N/A"
			     )
		     )
	* We would do the same for the sets sheet
* Can we remove the `module` string from the file names. The fact that they are a file already identifies them as a module.
	* parts-module -> parts-sheet
	* sets-module -> sets-sheet
	* dictionary-module -> odm-dictionary-file

2023-04-12 15:57 UTC, rvyuha commented
> * Can we standardize how we represent the information for the columns in a sheet? This can be done in another PR
>   
>   * I propose the following schema:
>     
>     * ```
>       list(
>           <column_list_name> = list(
>                 // Contains the name of the column in the sheet
>                 name = <column_name>,
>         	  // This is added only if the column is categorical
>         	  categories = list(
>         		  <category_list_name> = <category_identifier>
>         	  )
>           )
>       )
>       ```
>     * For the parts sheet the `list` would be (this list is abbreviated),
>       
>       * ```
>         list(
>             part_id = list(
>           	  name = "partID",
>             ),
>             part_type = list(
>           	  name = "partType",
>           	  categories = list(
>           		  tables = "tables"
>           	  )
>             )
>         )
>         ```
>     * Dynamic columns, columns whose names we don't know beforehand, like the table columns in the parts sheet are problematic.
>       
>       * We can store the information for those columns in a variable and then dynamically add to the schema in the code
>       * For example,
>       
>       ```
>         table_columns_metadata <- list(
>             categories = list(
>        	primary_key = "pK",
>        	foreign_key = "fK",
>        	header = "header",
>        	not_applicable = "N/A"
>             )
>         )
>       ```
>   * We would do the same for the sets sheet
> * Can we remove the `module` string from the file names. The fact that they are a file already identifies them as a module.
>   
>   * parts-module -> parts-sheet
>   * sets-module -> sets-sheet
>   * dictionary-module -> odm-dictionary-file

I agree with the schema approach however I am not sure if the dynamic columns even need to be stored?
I also agree that module is not the best suffix for the file name, but I still believe it would be best to distinguish that this file only stores strings related to that sheet not any functions.

2023-04-12 16:01 UTC, rvyuha commented
I noticed that most of your comments are about moving strings into function related files? I am not sure that is the best approach as it would mix string storage and functions. Is this the best approach for scalability? Wouldn't it make finding strings to modify more difficult?

2023-04-12 16:49 UTC, yulric commented
> I noticed that most of your comments are about moving strings into function related files? I am not sure that is the best approach as it would mix string storage and functions. Is this the best approach for scalability? Wouldn't it make finding strings to modify more difficult?

Deciding where to put a constant/function depends on the domain it deals with. For example the constants for parts sheet and functions that deal with the parts sheet should be in one module.

2023-04-14 13:14 UTC, rvyuha commented on R/dictionary-module.R
> +dictionary$dictionary_directory <- "data/raw"
Will move it once the merge occurs.

2023-04-19 12:14 UTC, yulric requested changes

2023-04-19 12:14 UTC, yulric commented on qmd/tables.qmd
> +parts$part_sheet_table_column_type_set_PK <- "Primary Key"
Why are you adding these to the `parts` object rather than as independent variables?

2023-04-19 12:14 UTC, yulric commented on R/qmd-utils.R
> +  odm_dictionary$parts_qmd_file_name <- "parts"
Why are you add these to the `odm_dictionary` object? Why can't you store them as independent variables?

2023-04-25 12:35 UTC, rvyuha commented
@yulric Ready for review

2023-04-25 15:52 UTC, yulric approved these changes

2023-05-30 14:54 UTC, merged